#!/bin/bash
function program_is_installed {
  # set to 1 initially
  local return_=1
  # set to 0 if not found
  type  >/dev/null 2>&1 || { local return_=0; }
  # return value
  echo ""
}

# AddUser
useradd ginga -s /sbin/nologin && su -s /bin/bash ginga

# Donwload, install, and activate nvm
if [ $(program_is_installed nvm ) == 0 ]
then
  # donwload and install nvm
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
  export NVM_DIR="$HOME/.nvm" [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  source ~/.bashrc

  # Installing specific node version for project
  nvm install 4.6.2
fi

# Install PM2
if [ $(program_is_installed npm ) == 0 ]
then
  npm install pm2 -g
fi

mkdir /gingasystems/apps/faber-api-mobile-poc
